name: Build Linux Binary
permissions:
  contents: write
  packages: write # 授予包的写入权限
on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (e.g., v0.1.3)"
        required: true
        default: "v0.1.3"

env:
  CARGO_TERM_COLOR: always

jobs:
  get-shoes-ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get-ref.outputs.ref }}
      version: ${{ steps.get-ref.outputs.version }}
    steps:
      - name: Determine ref and version
        id: get-ref
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ref=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "ref=master" >> $GITHUB_OUTPUT
            # 为 master 构建生成一个时间戳版本号
            echo "version=master-$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          fi
  build:
    needs: get-shoes-ref
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]

    steps:
      - name: Checkout shoes repository
        uses: actions/checkout@v4
        with:
          repository: cfal/shoes
          ref: ${{ needs.get-shoes-ref.outputs.ref }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - uses: Swatinem/rust-cache@v2

      - name: Build Release Binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Rename binary for release
        run: |
          cp target/${{ matrix.target }}/release/shoes shoes-${{ needs.get-shoes-ref.outputs.version }}-${{ matrix.target }}

      - name: Create Tag
        run: |
          git tag ${{ needs.get-shoes-ref.outputs.version }} || true
          git push origin ${{ needs.get-shoes-ref.outputs.version }} || true

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: shoes-${{ needs.get-shoes-ref.outputs.version }}-${{ matrix.target }}
          tag_name: ${{ needs.get-shoes-ref.outputs.version }}
          name: Release ${{ needs.get-shoes-ref.outputs.version }}
          body: "Linux binary build"
          draft: false
          prerelease: false
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List releases
        run: |
          echo "Checking for release: ${{ needs.get-shoes-ref.outputs.version }}"
          gh release list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download musl binary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const releaseTag = '${{ needs.get-shoes-ref.outputs.version }}';
            if (!releaseTag) {
              throw new Error('Release tag is empty');
            }

            const fileName = `shoes-${releaseTag}-x86_64-unknown-linux-musl`;
            console.log(`Searching for asset: ${fileName}`);

            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: releaseTag
              });

              const asset = release.data.assets.find(asset => asset.name === fileName);
              if (!asset) {
                throw new Error(`Asset ${fileName} not found in release`);
              }

              console.log(`Downloading asset from: ${asset.browser_download_url}`);
              const response = await fetch(asset.browser_download_url);
              if (!response.ok) {
                throw new Error(`Failed to download asset: ${response.statusText}`);
              }

              const buffer = await response.arrayBuffer();
              fs.writeFileSync('shoes', new Uint8Array(buffer));

              await exec.exec('chmod', ['+x', 'shoes']);
            } catch (error) {
              console.error('Error details:', error);
              throw error;
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            APP_VERSION=${{ needs.get-shoes-ref.outputs.version }}
            BINARY_NAME=shoes
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.get-shoes-ref.outputs.version }}
