name: Build Windows Binary
permissions:
  contents: write

on:
  # push:
  #   branches: [main, master]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (e.g., v0.1.3)"
        required: true
        default: "v0.1.3"

env:
  CARGO_TERM_COLOR: always

jobs:
  get-shoes-ref:
    runs-on: windows-latest
    outputs:
      ref: ${{ steps.get-ref.outputs.ref }}
      version: ${{ steps.get-ref.outputs.version }}
    steps:
      - name: Determine ref and version
        id: get-ref
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            echo "ref=${{ github.event.inputs.version }}" >> $env:GITHUB_OUTPUT
            echo "version=${{ github.event.inputs.version }}" >> $env:GITHUB_OUTPUT
          } else {
            echo "ref=master" >> $env:GITHUB_OUTPUT
            $timestamp = Get-Date -Format "yyyyMMddHHmm"
            echo "version=master-$timestamp" >> $env:GITHUB_OUTPUT
          }

  build:
    needs: get-shoes-ref
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]

    steps:
      - name: Checkout shoes repository
        uses: actions/checkout@v4
        with:
          repository: cfal/shoes
          ref: ${{ needs.get-shoes-ref.outputs.ref }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      # 因为代码使用了 `std::os::fd` 模块，但该模块在 Windows 平台上不可用，导致编译错误。
      - name: Build Release Binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Rename binary for release
        run: |
          copy target\${{ matrix.target }}\release\shoes.exe shoes-${{ needs.get-shoes-ref.outputs.version }}-${{ matrix.target }}.exe

      - name: Create Tag
        run: |
          git tag ${{ needs.get-shoes-ref.outputs.version }} || true
          git push origin ${{ needs.get-shoes-ref.outputs.version }} || true

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: shoes-${{ needs.get-shoes-ref.outputs.version }}-${{ matrix.target }}.exe
          tag_name: ${{ needs.get-shoes-ref.outputs.version }}
          name: Release ${{ needs.get-shoes-ref.outputs.version }}
          body: "Windows binary build"
          draft: false
          prerelease: false
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
