name: Build macOS Binary

on:
  # push:
  #   branches: [ main ]
  # 手动触发
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout shoes repository
        uses: actions/checkout@v4
        with:
          repository: cfal/shoes
          ref: v0.1.3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          profile: minimal
          override: true

      # 添加cargo缓存
      - uses: Swatinem/rust-cache@v2

      - name: Build Release Binary
        run: |
          cargo build --release --target aarch64-apple-darwin

      # 创建构建产物目录
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp target/aarch64-apple-darwin/release/shoes artifacts/shoes-v0.1.3-aarch64-apple-darwin

      # 上传到 Release
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/shoes-v0.1.3-aarch64-apple-darwin
          tag_name: v0.1.3 # Release 的标签名
          name: Release v0.1.3 # Release 的名称
          body: "MacOS M1 binary build" # Release 的描述
          repository: lekai63/docker-shoes # 仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的 token
