name: Build macOS Binary
permissions:
  contents: write
on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (e.g., v0.1.3)"
        required: true
        default: "v0.1.3"

env:
  CARGO_TERM_COLOR: always

jobs:
  get-shoes-ref:
    runs-on: macos-latest
    outputs:
      ref: ${{ steps.get-ref.outputs.ref }}
      version: ${{ steps.get-ref.outputs.version }}
    steps:
      - name: Determine ref and version
        id: get-ref
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ref=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "ref=master" >> $GITHUB_OUTPUT
            echo "version=master-$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          fi

  build:
    needs: get-shoes-ref
    runs-on: macos-latest
    strategy:
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin]

    steps:
      - name: Checkout shoes repository
        uses: actions/checkout@v4
        with:
          repository: cfal/shoes
          ref: ${{ needs.get-shoes-ref.outputs.ref }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Build Release Binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Rename binary for release
        run: |
          cp target/${{ matrix.target }}/release/shoes shoes-${{ needs.get-shoes-ref.outputs.version }}-${{ matrix.target }}

      - name: Create Tag
        run: |
          git tag ${{ needs.get-shoes-ref.outputs.version }} || true
          git push origin ${{ needs.get-shoes-ref.outputs.version }} || true

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: shoes-${{ needs.get-shoes-ref.outputs.version }}-${{ matrix.target }}
          tag_name: ${{ needs.get-shoes-ref.outputs.version }}
          name: Release ${{ needs.get-shoes-ref.outputs.version }}
          body: "macOS binary build for ${{ matrix.target }}"
          draft: false
          prerelease: false
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
